# Generated by Django 5.2.5 on 2025-09-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The manager of this employee.', limit_choices_to={'user_type': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee')], default='Manager', help_text='Select the type of user.', max_length=15, verbose_name='User Type'),
        ),
    ]
