# Generated by Django 5.2.5 on 2025-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_manager_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck this to 'freeze' or 'soft delete' the item. It will not be available for new operations.", verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck this to 'freeze' or 'soft delete' the item. It will not be available for new operations.", verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck this to 'freeze' or 'soft delete' the item. It will not be available for new operations.", verbose_name='Is Active'),
        ),
    ]
