# Generated by Django 5.2.5 on 2025-08-31 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calssification', models.CharField(blank=True, max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('phone_warehouse', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.inventorywarehouse', verbose_name='Parent Warehouse')),
            ],
            options={
                'verbose_name': 'Fuel Inventory Warehouse',
                'verbose_name_plural': 'Fuel Inventory Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryWarehouseitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit_of_measure', models.CharField(choices=[('Liters', 'Liters'), ('Barrel', 'Barrel'), ('Gallon', 'Gallon'), ('Units', 'Units')], default='Liters', max_length=50)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse', to='inventory.inventorywarehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_items', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Inventory Warehouse Item',
                'verbose_name_plural': 'Inventory Warehouse Items',
                'ordering': ['warehouse', 'item'],
            },
        ),
    ]
