# Generated by Django 5.2.5 on 2025-09-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorywarehouse',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='inventorywarehouse',
            name='storekeeper',
            field=models.ForeignKey(blank=True, help_text='The user responsible for this warehouse.', limit_choices_to={'user_type': 'Employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Storekeeper'),
        ),
    ]
