# Generated by Django 5.2.5 on 2025-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorywarehouse_manager_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorywarehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck this to 'freeze' or 'soft delete' the item. It will not be available for new operations.", verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck this to 'freeze' or 'soft delete' the item. It will not be available for new operations.", verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='stations',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck this to 'freeze' or 'soft delete' the item. It will not be available for new operations.", verbose_name='Is Active'),
        ),
    ]
