# Generated by Django 5.2.5 on 2025-09-11 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorywarehouse_is_active_item_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorywarehouse',
            name='storekeeper',
            field=models.ForeignKey(blank=True, help_text='The user responsible for this warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Storekeeper'),
        ),
    ]
