# Generated by Django 5.2.5 on 2025-08-31 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField()),
                ('paper_ref_number', models.DecimalField(decimal_places=0, default=0, help_text='Reference Paper Number', max_digits=20)),
                ('delivere_job_name', models.CharField(help_text='Delivere Name', max_length=255)),
                ('delivere_job_number', models.DecimalField(decimal_places=0, default=0, help_text='Delivere Job Number ', max_digits=20)),
                ('recipient_name', models.CharField(help_text='Recipient name', max_length=255)),
                ('recipient_job_number', models.CharField(help_text='Recipient Job Number', max_length=255)),
                ('operation_statement', models.TextField(blank=True, max_length=255)),
                ('operation_descrabtion', models.TextField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True, max_length=255)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_damage_operations', to='inventory.inventorywarehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ExportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_operation_date', models.DateTimeField()),
                ('paper_ref_number', models.DecimalField(decimal_places=0, default=0, help_text='Reference Paper Number', max_digits=20)),
                ('delivere_job_name', models.CharField(help_text='Delivere Name', max_length=255)),
                ('delivere_job_number', models.DecimalField(decimal_places=0, default=0, help_text='Delivere Job Number ', max_digits=20)),
                ('recipient_name', models.CharField(help_text='Recipient name', max_length=255)),
                ('recipient_job_number', models.CharField(help_text='Recipient Job Number', max_length=255)),
                ('date_transfer', models.DateTimeField()),
                ('date_actual_transfer', models.DateTimeField()),
                ('operation_statement', models.TextField(blank=True, max_length=255)),
                ('operation_descrabtion', models.TextField(blank=True, max_length=255)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reletions_to_beneficiary_model', to='accounts.beneficiary')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_export_operations', to='inventory.inventorywarehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDispatchOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(verbose_name='Return Date')),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Return')),
                ('paper_ref_number', models.CharField(blank=True, max_length=100, verbose_name='Paper Reference Number')),
                ('original_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='operations.exportoperation', verbose_name='Original Dispatch Operation')),
            ],
            options={
                'verbose_name': 'Return Dispatch Operation',
                'verbose_name_plural': 'Return Dispatch Operations',
            },
        ),
        migrations.CreateModel(
            name='SupplyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_start_date', models.DateTimeField()),
                ('paper_ref_number', models.DecimalField(decimal_places=0, default=0, help_text='Reference Paper Number', max_digits=20)),
                ('supply_bon_number', models.DecimalField(decimal_places=0, default=0, help_text='Supply Bond Number', max_digits=20)),
                ('delivere_job_name', models.CharField(help_text='Delivere Name ', max_length=255)),
                ('delivere_job_number', models.DecimalField(decimal_places=0, default=0, help_text='Delivere Job Number ', max_digits=20)),
                ('recipient_name', models.CharField(help_text='Recipient name', max_length=255)),
                ('recipient_job_number', models.CharField(help_text='Recipient Job Number', max_length=255)),
                ('operation_statement', models.TextField(blank=True, max_length=255)),
                ('operation_descrabtion', models.TextField(blank=True, max_length=255)),
                ('stations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reletions_to_stations_model', to='inventory.stations')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reletions_to_supplier_model', to='accounts.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_main_operations', to='inventory.inventorywarehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnSupplyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(verbose_name='Return Date')),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Return')),
                ('paper_ref_number', models.CharField(blank=True, max_length=100, verbose_name='Paper Reference Number')),
                ('original_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='operations.supplyoperation', verbose_name='Original Supply Operation')),
            ],
            options={
                'verbose_name': 'Return Supply Operation',
                'verbose_name_plural': 'Return Supply Operations',
            },
        ),
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField()),
                ('paper_ref_number', models.DecimalField(decimal_places=0, default=0, help_text='Reference Paper Number', max_digits=20)),
                ('delivere_job_name', models.CharField(help_text='Delivere Name', max_length=255)),
                ('delivere_job_number', models.DecimalField(decimal_places=0, default=0, help_text='Delivere Job Number ', max_digits=20)),
                ('recipient_name', models.CharField(help_text='Recipient name', max_length=255)),
                ('recipient_job_number', models.CharField(help_text='Recipient Job Number', max_length=255)),
                ('operation_statement', models.TextField(blank=True, max_length=255)),
                ('operation_descrabtion', models.TextField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True, max_length=255)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transfer_from_operations', to='inventory.inventorywarehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transfer_to_operations', to='inventory.inventorywarehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DamageOperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='item')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.damageoperation')),
            ],
            options={
                'unique_together': {('operation', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ExportOperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='item')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.exportoperation')),
            ],
            options={
                'unique_together': {('operation', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ReturnDispatchOperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Returned Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Item')),
                ('return_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='operations.returndispatchoperation')),
            ],
            options={
                'unique_together': {('return_operation', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ReturnSupplyOperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Returned Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Item')),
                ('return_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='operations.returnsupplyoperation')),
            ],
            options={
                'unique_together': {('return_operation', 'item')},
            },
        ),
        migrations.CreateModel(
            name='SupplyOperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='item')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.supplyoperation')),
            ],
            options={
                'unique_together': {('operation', 'item')},
            },
        ),
        migrations.CreateModel(
            name='TransferOperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='item')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.transferoperation')),
            ],
            options={
                'unique_together': {('operation', 'item')},
            },
        ),
    ]
