# Generated by Django 5.2.5 on 2025-08-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returndispatchoperationitem',
            old_name='returned_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='returnsupplyoperationitem',
            old_name='returned_quantity',
            new_name='quantity',
        ),
    ]
