# Generated by Django 5.2.5 on 2025-08-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_rename_returned_quantity_returndispatchoperationitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndispatchoperationitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total quantity of this item returned against this dispatch line.', max_digits=15, verbose_name='Returned Quantity'),
        ),
        migrations.AddField(
            model_name='returnsupplyoperationitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total quantity of this item returned against this supply line.', max_digits=15, verbose_name='Returned Quantity'),
        ),
    ]
