# Generated by Django 5.2.5 on 2025-08-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_returndispatchoperationitem_returned_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returndispatchoperationitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='returnsupplyoperationitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='exportoperationitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total quantity of this item returned against this dispatch line.', max_digits=15, verbose_name='Returned Quantity'),
        ),
        migrations.AddField(
            model_name='supplyoperationitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total quantity of this item returned against this dispatch line.', max_digits=15, verbose_name='Returned Quantity'),
        ),
        migrations.AlterField(
            model_name='returndispatchoperationitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Returned Quantity'),
        ),
        migrations.AlterField(
            model_name='returnsupplyoperationitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Returned Quantity'),
        ),
    ]
