# Generated by Django 5.2.5 on 2025-09-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('operations', '0004_remove_returndispatchoperationitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportoperation',
            old_name='export_operation_date',
            new_name='operation_date',
        ),
        migrations.RenameField(
            model_name='returndispatchoperation',
            old_name='return_date',
            new_name='operation_date',
        ),
        migrations.RenameField(
            model_name='returnsupplyoperation',
            old_name='return_date',
            new_name='operation_date',
        ),
        migrations.RenameField(
            model_name='supplyoperation',
            old_name='operation_start_date',
            new_name='operation_date',
        ),
        migrations.AlterField(
            model_name='supplyoperation',
            name='stations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reletions_to_stations_model', to='inventory.stations'),
            preserve_default=False,
        ),
    ]
