# Generated by Django 5.2.5 on 2025-09-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_rename_export_operation_date_exportoperation_operation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='operation_attachments/%Y/%m/%d', verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('damage_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.damageoperation')),
                ('export_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.exportoperation')),
                ('return_dispatch_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.returndispatchoperation')),
                ('return_supply_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.returnsupplyoperation')),
                ('supply_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.supplyoperation')),
                ('transfer_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.transferoperation')),
            ],
            options={
                'verbose_name': 'Operation Attachment',
                'verbose_name_plural': 'Operation Attachments',
            },
        ),
    ]
