# Generated by Django 5.2.5 on 2025-09-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_operationattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyExportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_item_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifications', to='operations.exportoperationitem')),
            ],
        ),
        migrations.CreateModel(
            name='ModifySupplyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_item_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifications', to='operations.supplyoperationitem')),
            ],
        ),
    ]
