# Generated by Django 5.2.5 on 2025-09-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_modifyexportoperation_modifysupplyoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifyexportoperation',
            name='operation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modifysupplyoperation',
            name='operation_date',
            field=models.DateTimeField(),
        ),
    ]
