# Generated by Django 5.2.5 on 2025-09-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_modifyexportoperation_operation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damageoperation',
            name='recipient_job_number',
        ),
        migrations.RemoveField(
            model_name='damageoperation',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='exportoperation',
            name='delivere_job_name',
        ),
        migrations.RemoveField(
            model_name='exportoperation',
            name='delivere_job_number',
        ),
        migrations.RemoveField(
            model_name='returndispatchoperation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='returnsupplyoperation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='supplyoperation',
            name='recipient_job_number',
        ),
        migrations.RemoveField(
            model_name='supplyoperation',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='recipient_job_number',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='damageoperation',
            name='recipient_user',
            field=models.ForeignKey(help_text='If the recipient is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_damage', to=settings.AUTH_USER_MODEL, verbose_name='Internal Recipient (if applicable)'),
        ),
        migrations.AddField(
            model_name='exportoperation',
            name='delivere_user',
            field=models.ForeignKey(help_text='If the delivere is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_export', to=settings.AUTH_USER_MODEL, verbose_name='Internal delivere (if applicable)'),
        ),
        migrations.AddField(
            model_name='modifyexportoperation',
            name='user',
            field=models.ForeignKey(help_text='If the delivere is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_modify_export', to=settings.AUTH_USER_MODEL, verbose_name='Internal delivere (if applicable)'),
        ),
        migrations.AddField(
            model_name='modifysupplyoperation',
            name='user',
            field=models.ForeignKey(help_text='If the delivere is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_modify_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Internal delivere (if applicable)'),
        ),
        migrations.AddField(
            model_name='returndispatchoperation',
            name='date_actual_transfer',
            field=models.DateTimeField(default='2025-09-01 01:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returndispatchoperation',
            name='date_transfer',
            field=models.DateTimeField(default='2025-09-01 01:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returndispatchoperation',
            name='delivere_user',
            field=models.ForeignKey(help_text='If the delivere is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_return_dispatch', to=settings.AUTH_USER_MODEL, verbose_name='Internal delivere (if applicable)'),
        ),
        migrations.AddField(
            model_name='returndispatchoperation',
            name='operation_descrabtion',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='returndispatchoperation',
            name='operation_statement',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='returndispatchoperation',
            name='recipient_job_number',
            field=models.CharField(default='2025-09-01 01:00:00', help_text='Recipient Job Number', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returndispatchoperation',
            name='recipient_name',
            field=models.CharField(default='2025-09-01 01:00:00', help_text='Recipient name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnsupplyoperation',
            name='date_actual_response',
            field=models.DateTimeField(default='2025-09-01 01:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnsupplyoperation',
            name='date_response',
            field=models.DateTimeField(default='2025-09-01 01:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnsupplyoperation',
            name='delivere_job_name',
            field=models.CharField(default='2025-09-01 01:00:00', help_text='Delivere Name ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnsupplyoperation',
            name='delivere_job_number',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Delivere Job Number ', max_digits=20),
        ),
        migrations.AddField(
            model_name='returnsupplyoperation',
            name='operation_descrabtion',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='returnsupplyoperation',
            name='operation_statement',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='returnsupplyoperation',
            name='recipient_user',
            field=models.ForeignKey(help_text='If the recipient is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_return_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Internal Recipient (if applicable)'),
        ),
        migrations.AddField(
            model_name='supplyoperation',
            name='recipient_user',
            field=models.ForeignKey(help_text='If the recipient is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Internal Recipient (if applicable)'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='recipient_user',
            field=models.ForeignKey(help_text='If the recipient is a registered user, select them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfer', to=settings.AUTH_USER_MODEL, verbose_name='Internal Recipient (if applicable)'),
        ),
        migrations.AlterField(
            model_name='damageoperation',
            name='delivere_job_name',
            field=models.CharField(help_text='Delivere Name ', max_length=255),
        ),
        migrations.AlterField(
            model_name='transferoperation',
            name='delivere_job_name',
            field=models.CharField(help_text='Delivere Name ', max_length=255),
        ),
    ]
