# Generated by Django 5.2.5 on 2025-09-06 22:07

import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_damageoperation_recipient_job_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationattachment',
            name='file',
            field=models.FileField(upload_to=operations.models.OperationAttachment.operation_attachment_path, verbose_name='File'),
        ),
    ]
